name = "Dimension Frontier"
author = "Twister716"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c687a6c3c0c8f7a66aed8454c5e975782d43de3e6ffe7128cc04e79eef2e29cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
