name = "Dimension Frontier"
author = "Twister716"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7273e873a0ec7ba050368ef5001b597b91f255056f33caea049f742bebea138"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
