[debug]
	# 項目名：デバッグ材料
	# 説明：JEIの材料フィルターに、追加および更新されたアイテムのログを記録します。
	# 有効値：[true, false]
	# デフォルト値：false
	debugIngredientsEnabled = false

	# 項目名：デバッグGUI
	# 説明：デバッグGUIモードを有効化します。
	# 有効値：[true, false]
	# デフォルト値：false
	debugGuis = false

	# 項目名：デバッグ入力
	# 説明：デバッグ入力モードを有効化します。
	# 有効値：[true, false]
	# デフォルト値：false
	debugInputs = false

	# 項目名：デバッグ説明ツールチップ
	# 説明：高度な情報が有効化されているとき、アイテムのツールチップにデバッグ情報を追加します。
	# 有効値：[true, false]
	# デフォルト値：false
	debugInfoTooltipsEnabled = false

	# 項目名：統計ツリーの記録
	# 説明：JEIのデバッグを補助するために、検索に使用された接尾辞ツリーに関する情報をログに記録します。
	# 有効値：[true, false]
	# デフォルト値：false
	logSuffixTreeStats = false


