#Enable Draconic Render Patch.
enableFix = true
#Force enableUnknownShaders to true in Iris to ensure Draconic Evolution entity render. This will try to override Iris settings.
enableIrisCompat = true
#Force ImmediatelyFast runtime hud_batching to false to ensure Draconic Evolution's items can render in hud.
enableImmediatelyFastCompat = true
