["food effects tooltip"]
	#Show suspicious stew food effects tooltips
	showSuspiciousStewTooltips = false
	#Whitelisted Item.
	whitelistItems = ["modid:testitem"]
	#Whitelisted Item.
	whitelistModsIDs = ["modid"]
	#Blacklisted Item.
	blacklistItems = ["modid:testitem"]
	#Blacklisted Mod IDs.
	blacklistModsIDs = ["modid", "farmersdelight", "expandeddelight", "moredelight", "oceansdelight", "ubesdelight", "vinery"]
	#Default tooltip behavior for unlisted items
	#Allowed Values: SHOW, HIDE
	defaultTooltipBehavior = "SHOW"
