#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 23:55:10 JST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
